batch_size: 2
workers: 4
nepoch: 1
model_name: PointAttN
load_model:  False
start_epoch: 0
num_points_input: 6000
is_rgb: False
work_dir: log/
flag: debug
loss: cd #cd
manual_seed: null # 1748
step_interval_to_print: 100
epoch_interval_to_save: 1
epoch_interval_to_val: 1

lr: 0.0001
lr_d: 0.0001
lr_scheduler: LinelrCosineAnnealing
lr_decay: True
lr_decay_interval: 20
lr_decay_rate: 0.7
lr_step_decay_epochs: null
lr_step_decay_rates: null
lr_clip: 1.e-6
optimizer: Adam
weight_decay: 0
betas: 0.9, 0.999

device: '0'
dataset: 'mydata'
pcnpath: $PATH/ShapeNetCompletion
c3dpath: /media/zhutianyu/6D6A209A6663F595/ubuntushare/zty/dataset-all/shapenet
mydatapath: /media/zhutianyu/6D6A209A6663F595/ubuntushare/zty/dataset-all/果实数据增强
# test
save_vis: False
